// MyBookings
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKINGS_ERROR = 'GET_BOOKINGS_ERROR';
export const DELETE_BOOKINGS_SUCCESS = 'DELETE_BOOKINGS_SUCCESS';
export const DELETE_BOOKINGS_ERROR = 'DELETE_BOOKINGS_ERROR';
export const EDIT_BOOKINGS_SUCCESS = 'EDIT_BOOKINGS_SUCCESS';
export const EDIT_BOOKINGS_ERROR = 'EDIT_BOOKINGS_ERROR';
export const ADD_BOOKINGS_SUCCESS = 'ADD_BOOKINGS_SUCCESS';
export const ADD_BOOKINGS_ERROR = 'ADD_BOOKINGS_ERROR';
export const GET_PROFILE_BOOKINGS_SUCCESS = 'GET_PROFILE_BOOKINGS_SUCCESS';
export const GET_PROFILE_BOOKINGS_ERROR = 'GET_PROFILE_BOOKINGS_ERROR';

// MyClients
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_ERROR = 'ADD_CLIENT_ERROR';
